version: '3'

services:
  db:
    image: 'mysql:8.0'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-mysql-db-pwd
      MYSQL_DATABASE: copsbootdb

  identity:
    image: 'quay.io/keycloak/keycloak:22.0.1'
    entrypoint: >
      /opt/keycloak/bin/kc.sh start-dev --import-realm
    ports:
      - '8180:8080'
    environment:
      KEYCLOAK_LOGLEVEL: 'INFO'
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin-secret'
      KC_HOSTNAME: 'localhost'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
    volumes:
      - ./realms:/opt/keycloak/data/import
